### ISSUE TITLE
Under Windows, the built-in nvidia 1050 cannot be scanned by lspci,but 1070ti works fine

### ISSUE THREAD

**Issue by liujian883** [pciutils/pciutils#40] opened 2020-03-24 03:38 UTC
Hello, 
      I have an XPS laptop with a built-in nvidia 1050 graphics card and an external nvidia 1070ti graphics card via thunderbolt 3.Under Windows (which I compiled myself), I found that my 1070ti, which was connected to thunderbolt 3, could be scanned normally(with i386-io-windows.h), but the 1050 inside the laptop could not.After analyzing the source code, I found that in the pci_generic_scan_bus function, pci_read_long(PCI_VENDOR_ID), returns the value 0xffffffff.May I ask why?Under Linux, 1050 can be scanned by lspci.Through the Windows device manager, I see that bus for 1050 is 0x1, dev is 0x0, and func is 0x0
    thanks!

**Comment by gollux** [comment] 2020-05-25 13:34
Sorry, the Windows back-end currently lacks a maintainer. If you know anybody who would be willing to do that, please let me know.

**Comment by pali** [comment] 2022-01-01 21:01
@liujian883: Is this XPS laptop with dual switchable GPU cards (Intel / Nvidia)?

Dedicated internal GPU (both AMD and Nvidia) in more laptops for power saving is with some drivers (glued to ACPI) automatically turned off (or put into some deep sleep state) when card is not used. In this semi-broken state it does not respond to PCIe config transactions and host bridge returns back to CPU PCIe CA response... which for read operation generates fabricated all-ones response (0xffffffff). This HW design does not use proper PCIe hotplug and power management features so it means that card is always visible in OS (sysfs on Linux, Device Manager on Windows). But direct access to PCI config space skipping OS has same result as if card is not connected in system at all. Running `lspci -A intel-conf1` on Linux should have same effect. Drivers for those cards has some ACPI glue code which use some platform specific method to wake up card as standard PCIe path does not work.

External GPU has probably better HW implementation of PCIe hotplug and PCIe ASPM features. So trying to send PCIe config transaction correctly put card from some powersave L* state to L0 before transaction is transmitted.

I can reproduce this issue (that direct access to config space always returns all-ones) on more dedicated internal GPU cards in laptops.

**Comment by gollux** [comment] 2024-02-18 00:48
Since we now have proper Windows back-ends, I am closing this bug. If you experience the problem with current pciutils, feel free to re-open the issue.

**Closed by gollux** 2024-02-18 00:48 UTC
Labels: help wanted, Windows
