### ISSUE TITLE
Display PCIe Device Power Consumption

### ISSUE THREAD

**Issue by KobayashiD27** [pciutils/pciutils#180] opened 2024-04-22 06:49 UTC
The objective is to check the power consumption of PCIe devices.

The PCIe specification includes two features, Power Management (PM) and Power Budgeting Extended Capability (PBEC), which can be used to check power consumption.
However, the current implementation of lspci only partially displays PM information, and does not include the power consumption values. Additionally, PBEC is not implemented at all.

The PM output includes D_sel, D_scale, and Data values, which can be used to calculate power consumption. I propose to implement an addition to calculate and display the power consumption values based on these parameters.
Output likes this (Add the bottom output):
```
Capabilities: [c8] Power Management version 2
         Flags: PMEClk- DSI+ D1- D2- AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
         Status: D0 NoSoftRst- PME-Enable- DSel=0 DScale=0 PME-
         Data: D0 Power Consumed, xxxW
```

And, PBEC 
I propose the following format for the PBEC output:

```
Capabilities: [138 v1] Power Budgeting
         PBCtl: ExPB+ PowLim+ PLPMSubSt=D0 OoBPowLim- OoBPowLimPMSubSt=D0
         PBCap: SysAllo+ ExPB+ PBSenDet+ PowLim+ PowDis=00 PowLosNotif=00
         Data:  D0 Power: 9.0W Type: Auxiliary PowerRail: Power(3.3V)
                D1 Power: 8.0W Type: Auxiliary PowerRail: Power(3.3V)
                D2 Power: 5.5W Type: Auxiliary PowerRail: Power(3.3V)
         SenseData: aaa
```

This implementation requires extracting and displaying the power state and consumption pairs from the PBEC information.
I haven't tried it yet, but I'm thinking of implementing something like the following:
```
while(){
  pci_write_byte(d, where + PCI_PWR_DSR, index);
  l = get_conf_long(d, where + PCI_PWR_DATA);
  printf("Data: D0 Power: %dW Type: %s, PowerRail: Power(%fV)\n", 
              FLAG(l, PCI_PWR_DATA_PM_STATE),
              FLAG(l, PCI_PWR_DATA_TYPE),
              FLAG(l, PCI_PWR_DATA_RAIL));
  index++;
  if(xxxx) break;
}
```

What do you think about the above features and implementation policies?
Is it a better procedure to implement first and make a PR?

**Comment by gollux** [comment] 2024-04-23 12:20
The problem is that reading the PBEC information requires writing to the configuration space, which is generally very unsafe - the same registers could be accessed by other programs simultaneously (other instances of lspci, but most importantly the OS).

The right solution is to implement a driver for that and let lspci display information provided by the driver.

On the other hand, I understand that when debugging hardware, people sometimes want to poke it directly without relying on OS support. So it might make sense to add a special option like `lspci --unsafe-pbec` which enables poking the registers. But it must never be the default.

**Comment by KobayashiD27** [comment] 2024-04-24 09:43
Thank you for your feedback.

Regarding PBRC, I understand the concern that the register could be accessed by other programs simultaneously, making it unsafe. My ideal is to only write to PBEC and output the value when the option is enabled.
If the register write is only performed when a specific option is specified, I believe that unintended conflicts will not occur. (all user intend to write a register)

The PM is not currently outputting the value of Data. Is there a reason for this? If not, I would like to implement the output of PM's power consumption and submit a PR.

I plan to implement this policy. Please let me know if there are any problems or improvements.

**Comment by gollux** [comment] 2024-04-24 12:31
I think that it's better to do it in the same way is you did with CXL link status: read it in the kernel and add a sysfs attribute for that. This will make the feature useful for all users.

**Comment by KobayashiD27** [comment] 2024-04-25 08:36
I see. I will consider another method in using kernel driver.
I may ask you a question again, but I look forward to your cooperation in that case.

**Comment by gollux** [comment] 2024-05-27 12:23
OK, I am closing this for now. Feel free to re-open it or file a new issue when you have something ready.

**Closed by gollux** 2024-05-27 12:23 UTC
